### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by danpantry** [danpantry/whatthefuckshouldiplaynow.com#1]
#### Authentication
- [ ] Enable authentication with Google+
- [ ] Enable authentication with Facebook
- [ ] Enable authentication with Twitter

#### Game Recommendations
- [ ] Show users recommendations for games based on the genre of games they have recently played.
- [ ] Allow users to mark games as 'irrelevant' when suggested. If a player does so, 'weaken' the link between the games they have played and the suggested game such that that game is suggested *less* to other users with a similar game library.
- [ ] Allow users to mark games as 'relevant', which does the exact opposite of 'irrelevant' - it strengthens the link.
- [ ] Leaving a positive review on a game should also strengthen the 'global' linkage of a game, i.e, the more positive reviews a game gets, the more likely it should be to appear on *all* recommendation paths.
- [ ] Leaving a negative review should do the exact opposite of leaving a positive review.
- [ ] The alteration of these links should be done in such a way that one user cannot influence the entire game link. That is to say, companies should not be able to promote their own game with a few upvotes, nor be able to vastly screw over an opposing game with a few downvotes. In other words, see Reddit with vote fuzzing.

#### Game Search
- [ ] Enable users to search and enter games they have played previously from an internal library
- [ ] If a game isn't found in the library, allow a user to specify that game with a URL and enter that game into a queue to be manually have details entered by an administrator?

#### Games
- [ ] Enable users to leave a review on a game (one or two paragraphs plus a positive/negative rating).
- [ ] Show aggregation of all ratings on a single game.
- [ ] Enable users to save a game to their 'favourites', which will show up on their profile and in a news feed.

##### Steam Games
- [ ] Show current price of game on Steam if applicable
- [ ] Show link to Steam Store page if applicable

#### News Feed
- [ ] Display recent 'favourites' and ratings of friends.
- [ ] Display site news bulletins.

#### Social
- [ ] Enable users to add/remove friends.
- [ ] Auto-sync friends from Facebook if given permission.
- [ ] Friends should show up in a friends list on the users profile.
